# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shayer Dags
tagline:          'A Jekyll theme'
description:      'A designer, digital marketer, and all-around computer nerd who stands on the shoulders of giants."
url:              http://ppmanforthewin.github.io
baseurl:          /hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
